---
- name: Set variables
  set_fact:
    host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    host_name: "{{ inventory_hostname_short }}"

- name: Initialize the Kubernetes cluster
  ansible.builtin.command: kubeadm init --apiserver-advertise-address={{ host_ip }} --apiserver-cert-extra-sans={{ host_ip }} --pod-network-cidr={{ pod_network_range }} --node-name {{ host_name }} --ignore-preflight-errors Swap

- name: Create the .kube directory
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copy the Kubernetes admin.conf to the newly created directory
  ansible.builtin.command: cp -i /etc/kubernetes/admin.conf /root/.kube/config

- name: Set permissions on the .kube/config directory
  ansible.builtin.command: chown root:root /root/.kube/config

- name: Print the join token
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_token

- name: Create a fake host so we can make the join token accessible by the next play
  add_host:
    name: "variable_store"
    join_token: "{{ join_token.stdout }}"